// AUTO-GENERATED by scripts--i18n_apply (Chantan).
// Regenerated on every i18n_apply run. Manual edits to this file get
// overwritten — to customize, ask the AI to "make the language toggle
// <your change>" and the regen will incorporate it. Or move the toggle
// out of this file entirely (e.g. inline into Navbar).

import { useTranslation } from "react-i18next"

const LABELS: Record<string, { short: string; native: string }> = {
  "en": { short: "EN", native: "English" },
  "th": { short: "TH", native: "ไทย" }
}

const ORDER = ["en","th"]

export function LanguageToggle() {
  const { i18n } = useTranslation()
  const current = ORDER.includes(i18n.language) ? i18n.language : ORDER[0]
  const next = ORDER[(ORDER.indexOf(current) + 1) % ORDER.length]
  const label = LABELS[next]?.short || next.toUpperCase()

  return (
    <button
      type="button"
      onClick={() => i18n.changeLanguage(next)}
      className="text-sm font-semibold px-3 py-1.5 rounded-full border border-border text-foreground hover:bg-accent transition-colors"
      aria-label={`Switch to ${LABELS[next]?.native || next}`}
    >
      {label}
    </button>
  )
}
